### ISSUE TITLE
Minimap thru events

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/principled-design-com#17]
Moving the minimap indicator thru events instead of explicitly make a function call might improve performance. I mean, trigger a move event fmor `Site.Map` and listen it from `Site.Minimap`. The event could contain the `x,y` data needed.

https://github.com/interglobalvision/principled-design-com/blob/master/src/js/main.js#L443

See `startpan` and `stoppan` eventint he code for reference.

In the debugger this functions takes the most to return, blocking the code execution. We don't need this function to return, thats why i think events would make it better.

**Comment by varffs** [comment]
I don't understand what you are saying here. But generally we need a perf boost so is it worth you trying to do this quickly?
