### ISSUE TITLE
background pattern change should stop when panning is still

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/principled-design-com#56]
idk how to achieve this

**Comment by mikeyrayvon** [comment]
i told them we might not get to this. they seemed ok with that

**Comment by mikeyrayvon** [comment]
actually i do know what to do. we only need to look for the corners and the middle points. set a boolean when we get there, and change it when we leave. and check for that before changing the background shape

**Comment by varffs** [comment]
I think it is part of the panning function really. The panning action should somehow stop once it can't pan anymore. At the moment I think the moving of the map is still being triggered but just to the position the map is already in
